/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author lucas
 */
public class Calculadora extends javax.swing.JFrame {
       
    
    double num, resp;
    int calculation;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
               
    }

        public void calculo(){
    switch(calculation){
        case 1: {
            resp = num + Double.parseDouble(jtfTela.getText());
            jtfTela.setText(Double.toString(resp));
            break;
        }
        case 2:{
            resp = num - Double.parseDouble(jtfTela.getText());
            jtfTela.setText(Double.toString(resp));
            break;
        }
        case 3: {
            resp = num * Double.parseDouble(jtfTela.getText());
            jtfTela.setText(Double.toString(resp));
            break;
        }
        case 4: {
            resp = num / Double.parseDouble(jtfTela.getText());
            jtfTela.setText(Double.toString(resp));
            break;
        }
    }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JBponto = new javax.swing.JButton();
        JBdel = new javax.swing.JButton();
        JBmult = new javax.swing.JButton();
        JBdiv = new javax.swing.JButton();
        JBsub = new javax.swing.JButton();
        JBsoma = new javax.swing.JButton();
        JBclear = new javax.swing.JButton();
        jtfTela = new javax.swing.JTextField();
        JBigual = new javax.swing.JButton();
        jtlNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB2.setText("2");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB3.setText("3");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JB1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB1.setText("1");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB4.setText("4");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB5.setText("5");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB6.setText("6");
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JB0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB0.setText("0");
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        JB7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB7.setText("7");
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB8.setText("8");
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JB9.setText("9");
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JBponto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBponto.setText(".");
        JBponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpontoActionPerformed(evt);
            }
        });

        JBdel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBdel.setText("Del");
        JBdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdelActionPerformed(evt);
            }
        });

        JBmult.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBmult.setText("X");
        JBmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmultActionPerformed(evt);
            }
        });

        JBdiv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBdiv.setText("÷");
        JBdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdivActionPerformed(evt);
            }
        });

        JBsub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBsub.setText("-");
        JBsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsubActionPerformed(evt);
            }
        });

        JBsoma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBsoma.setText("+");
        JBsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsomaActionPerformed(evt);
            }
        });

        JBclear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBclear.setText("AC");
        JBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBclearActionPerformed(evt);
            }
        });

        jtfTela.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTela.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        JBigual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBigual.setText("=");
        JBigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBigualActionPerformed(evt);
            }
        });

        jtlNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtlNum.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfTela, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JBdel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JBsub, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JBdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JBmult, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JBclear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBponto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JBigual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jtlNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTela, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBmult, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBsub, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBponto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBdel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBclear, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBigual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JBsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
       jtfTela.setText(jtfTela.getText() + "2");
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
       jtfTela.setText(jtfTela.getText() + "3");
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        jtfTela.setText(jtfTela.getText() + "1");
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
       jtfTela.setText(jtfTela.getText() + "4");
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        jtfTela.setText(jtfTela.getText() + "5");
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
      jtfTela.setText(jtfTela.getText() + "6");
    }//GEN-LAST:event_JB6ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
       jtfTela.setText(jtfTela.getText() + "0");
    }//GEN-LAST:event_JB0ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
       jtfTela.setText(jtfTela.getText() + "7");
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        jtfTela.setText(jtfTela.getText() + "8");
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
      jtfTela.setText(jtfTela.getText() + "9");
    }//GEN-LAST:event_JB9ActionPerformed

    private void JBpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpontoActionPerformed
      jtfTela.setText(jtfTela.getText() + ".");
    }//GEN-LAST:event_JBpontoActionPerformed

    private void JBdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdelActionPerformed
       int lenght = jtfTela.getText().length();
       int number = jtfTela.getText().length() -1;
       String store;
       
       if (lenght > 0){
           StringBuilder back = new StringBuilder(jtfTela.getText());    
           back.deleteCharAt(number);
           store = back.toString();
           jtfTela.setText(store);
       }
    }//GEN-LAST:event_JBdelActionPerformed

    private void JBmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmultActionPerformed
       num = Double.parseDouble(jtfTela.getText());
        calculation = 3;
        jtfTela.setText("");
        jtlNum.setText(num + "X");
    }//GEN-LAST:event_JBmultActionPerformed

    private void JBdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdivActionPerformed
        num = Double.parseDouble(jtfTela.getText());
        calculation = 4;
        jtfTela.setText("");
        jtlNum.setText(num + "÷");
    }//GEN-LAST:event_JBdivActionPerformed

    private void JBsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsubActionPerformed
      num = Double.parseDouble(jtfTela.getText());
        calculation = 2;
        jtfTela.setText("");
        jtlNum.setText(num + "-");
    }//GEN-LAST:event_JBsubActionPerformed

    private void JBsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsomaActionPerformed
        num = Double.parseDouble(jtfTela.getText());
        calculation = 1;
        jtfTela.setText("");
        jtlNum.setText(num + "+");
    }//GEN-LAST:event_JBsomaActionPerformed

    private void JBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBclearActionPerformed
       jtfTela.setText("");
    }//GEN-LAST:event_JBclearActionPerformed

    private void JBigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBigualActionPerformed
        calculo();
        jtlNum.setText("");
    }//GEN-LAST:event_JBigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBclear;
    private javax.swing.JButton JBdel;
    private javax.swing.JButton JBdiv;
    private javax.swing.JButton JBigual;
    private javax.swing.JButton JBmult;
    private javax.swing.JButton JBponto;
    private javax.swing.JButton JBsoma;
    private javax.swing.JButton JBsub;
    private javax.swing.JTextField jtfTela;
    private javax.swing.JLabel jtlNum;
    // End of variables declaration//GEN-END:variables

  
}
